# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: usl_pipeline CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo add-apt-repository ppa:ubuntugis/ppa -y
        sudo apt-get update -qq
        sudo apt-get install -y gdal-bin libgdal-dev
        python -m pip install --upgrade pip
        pip install -r usl_pipeline/requirements.txt
        pip install -e usl_pipeline[dev]
    - name: Lint with flake8
      run: |
        flake8 usl_pipeline --show-source --statistics
    - name: Ensure black auto-formatter has run
      run: |
        black usl_pipeline --check
    - name: Test with pytest
      run: |
        pytest usl_pipeline
